### ISSUE TITLE
Segfault with V8::Context.new(:with => foo) special case

### ISSUE THREAD

**Issue by dmcinnes** [cowboyd/therubyracer#251]
I've been running into a problem with segfaults when using :with with more than just simple objects.

If the passed in context object has a reference to an external object it segfaults.
Here's some example code that dumps every time:

```ruby
require 'v8'

class Foo
  def initialize(hash)
    @hash = hash
  end
end

data = {}

v8 = V8::Context.new(:with => Foo.new(data))
```

and the dump:

```
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:62: [BUG] Segmentation fault
ruby 1.9.2p320 (2012-04-20) [x86_64-darwin11.4.0]

-- control frame ----------
c:0018 p:---- s:0053 b:0053 l:000052 d:000052 CFUNC  :New
c:0017 p:0049 s:0048 b:0048 l:001f28 d:000047 BLOCK  /Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:62
c:0016 p:0028 s:0045 b:0045 l:001f50 d:000044 BLOCK  /Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:235
c:0015 p:---- s:0043 b:0043 l:000042 d:000042 FINISH
c:0014 p:---- s:0041 b:0041 l:000040 d:000040 CFUNC  :call
c:0013 p:---- s:0039 b:0039 l:000038 d:000038 CFUNC  :HandleScope
c:0012 p:0017 s:0036 b:0036 l:001f50 d:000448 BLOCK  /Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:232
c:0011 p:---- s:0034 b:0034 l:000033 d:000033 FINISH
c:0010 p:---- s:0032 b:0032 l:000031 d:000031 CFUNC  :call
c:0009 p:---- s:0030 b:0030 l:000029 d:000029 CFUNC  :Locker
c:0008 p:0053 s:0027 b:0027 l:001f50 d:001f50 METHOD /Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:231
c:0007 p:0026 s:0023 b:0023 l:000022 d:000022 METHOD /Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:191
c:0006 p:0076 s:0019 b:0019 l:001f28 d:001f28 METHOD /Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:60
c:0005 p:---- s:0014 b:0014 l:000013 d:000013 FINISH
c:0004 p:---- s:0012 b:0012 l:000011 d:000011 CFUNC  :new
c:0003 p:0066 s:0008 b:0008 l:000588 d:002088 EVAL   test.rb:11
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:000588 d:000588 TOP
---------------------------
-- Ruby level backtrace information ----------------------------------------
test.rb:11:in `<main>'
test.rb:11:in `new'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:60:in `initialize'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:191:in `enter'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:231:in `lock_scope_and_enter'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:231:in `Locker'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:231:in `call'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:232:in `block in lock_scope_and_enter'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:232:in `HandleScope'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:232:in `call'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:235:in `block (2 levels) in lock_scope_and_enter'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:62:in `block in initialize'
/Users/dmcinnes/.rvm/gems/ruby-1.9.2-p320/gems/therubyracer-0.11.2/lib/v8/context.rb:62:in `New'

-- C level backtrace information -------------------------------------------

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

I've been getting around this problem by not using :with and doing this for each method:
```ruby
v8['method_name'] = foo.method('method_name')
```
But it would be nice to pass in the object directly.

**Comment by cowboyd** [comment]
dup of #241, which will be resolved in 1.0
