### ISSUE TITLE
Doesn't build/install on ARM (Raspberry Pi armv6l)

### ISSUE THREAD

**Issue by lunij** [cowboyd/therubyracer#257]
`gem 'therubyracer', :github => 'cowboyd/therubyracer'`

If I run bundle like that, it installs libv8 (3.16.14.1) without problems. But therubyracer (0.12.0beta1) fails because of the following reason:

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /home/pi/.rvm/rubies/ruby-1.9.3-p374/bin/ruby extconf.rb
checking for main() in -lpthread... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/pi/.rvm/rubies/ruby-1.9.3-p374/bin/ruby
        --with-pthreadlib
        --without-pthreadlib
        --enable-debug
        --disable-debug
        --with-v8-dir
        --without-v8-dir
        --with-v8-include
        --without-v8-include=${v8-dir}/include
        --with-v8-lib
        --without-v8-lib=${v8-dir}/
/home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/gems/libv8-3.16.14.1/ext/libv8/location.rb:50:in `configure': You have chosen to use the version of V8 found on your system (Libv8::Location::System::NotFoundError)
and *not* the one that is bundle with the libv8 rubygem. However,
it could not be located. please make sure you have a version of
v8 that is compatible with 3.16.14.1 installed. You may
need to special --with-v8-dir options if it is in a non-standard
location

thanks,
The Mgmt

        from /home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/gems/libv8-3.16.14.1/lib/libv8.rb:7:in `configure_makefile'
        from extconf.rb:32:in `<main>'


Gem files will remain installed in /home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/bundler/gems/therubyracer-3b157e9557d3 for inspection.
Results logged to /home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/bundler/gems/therubyracer-3b157e9557d3/ext/v8/gem_make.out

An error occurred while installing therubyracer (0.12.0beta1), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.12.0beta1'` succeeds before bundling.
```

When I do this via rubygems ...

`gem 'therubyracer', '0.11.4', :platforms => :ruby``

... it installs libv8 (3.11.8.17). But it also runs into the same problem.

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /home/pi/.rvm/rubies/ruby-1.9.3-p374/bin/ruby extconf.rb
checking for main() in -lpthread... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/pi/.rvm/rubies/ruby-1.9.3-p374/bin/ruby
        --with-pthreadlib
        --without-pthreadlib
        --enable-debug
        --disable-debug
        --with-v8-dir
        --without-v8-dir
        --with-v8-include
        --without-v8-include=${v8-dir}/include
        --with-v8-lib
        --without-v8-lib=${v8-dir}/
/home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/gems/libv8-3.11.8.17/ext/libv8/location.rb:50:in `configure': You have chosen to use the version of V8 found on your system (Libv8::Location::System::NotFoundError)
and *not* the one that is bundle with the libv8 rubygem. However,
it could not be located. please make sure you have a version of
v8 that is compatible with 3.11.8.17 installed. You may
need to special --with-v8-dir options if it is in a non-standard
location

thanks,
The Mgmt

        from /home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/gems/libv8-3.11.8.17/lib/libv8.rb:7:in `configure_makefile'
        from extconf.rb:32:in `<main>'


Gem files will remain installed in /home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/gems/therubyracer-0.11.4 for inspection.
Results logged to /home/pi/.rvm/gems/ruby-1.9.3-p374@xbeetempmesh/gems/therubyracer-0.11.4/ext/v8/gem_make.out

An error occurred while installing therubyracer (0.11.4), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.
```

Why it tells me that I have chosen to use the version of V8 found on my system now? I doesn't use the `--system-v8` option anymore. Before this, I got other errors because of libv8. It wasn't possible to install it. I started to build libv8 on my own. I cloned the Github repo, modified the version string of libv8 to get a newer version of V8 and forced the V8 Makefile to checkout the newest version of gyp. After all, the build was successfully. I had a libv8 (version 3.19.1.0 armv6l-linux) installed in my gemset. Problem was, therubyracer couldn't handle such a new version of libv8/V8.

I cleaned up all my libv8 gems and started from the beginning. Now libv8 installs without problems. I have **no** system-v8 installed. Unfortunately, therubyracer doesn't want to get installed.

**Comment by ChrisFernandez** [comment]
@kaushalsanghavi   were you able to find a solution? Im trying to install therubyracer and still have issues.. even do I do have libv8 installed.. libv8 (3.3.10.4)
