### ISSUE TITLE
Assertion failed error on installation

### ISSUE THREAD

**Issue by purecreative** [cowboyd/therubyracer#386]
Trying to install therubyracer 0.12.2 using Windows:

gem install therubyracer -v '0.12.2'

The installation fails with:

```
ERROR:  Error installing therubyracer:
ERROR: Failed to build gem native extension.

C:/Ruby22/bin/ruby.exe -r ./siteconf20150820-15920-1e07sjp.rb extconf.rb
creating Makefile
Assertion failed: hunk, file patch.c, line 321

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/patcher.rb:50:in `
block (2 levels) in patch!': failed to apply patch (RuntimeError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/patch
er.rb:48:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/patch
er.rb:48:in `block in patch!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/patch
er.rb:44:in `open'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/patch
er.rb:44:in `patch!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/build
er.rb:57:in `block in build_libv8!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/build
er.rb:52:in `chdir'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/build
er.rb:52:in `build_libv8!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.11/ext/libv8/locat
ion.rb:24:in `install!'
        from extconf.rb:7:in `<main>'

extconf failed, exit code 
```
From what I can gather this is to do with the way that Windows treats line feeds as opposed to Unix when working with patch/diff files. I don't know how to get round this and apply the patch.

**Comment by navrocky** [comment]
I confirm this bug

**Comment by ignisf** [comment]
There's still no official support for Windows for `therubyracer`. However I'm finding information that this assert fails when one tries to apply a patch file with only `LF` line terminations on Windows. See http://gnuwin32.sourceforge.net/packages/patch.htm

Could you give us more information about your environments? Are you using the DevKit? Which version?

**Comment by purecreative** [comment]
Using Ruby version:
ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]

DevKit is installed version:
DevKit-mingw64-32-4.7.2-20130224-1151-sfx
