### ISSUE TITLE
 __isnan: symbol not found

### ISSUE THREAD

**Issue by atwoodjw** [cowboyd/therubyracer#404]
I'm seeing ` __isnan: symbol not found` when precompiling assets. Both 'therubyracer' and 'libv8' are in the bundle and installed without error.

```
[WARNING] Please install gem 'therubyracer' to use Less.
rake aborted!
LoadError: Error relocating /usr/local/bundle/gems/therubyracer-0.12.2/lib/v8/init.so: __isnan: symbol not found - /usr/local/bundle/gems/therubyracer-0.12.2/lib/v8/init.so
/usr/local/bundle/gems/therubyracer-0.12.2/lib/v8.rb:4:in `require'
/usr/local/bundle/gems/therubyracer-0.12.2/lib/v8.rb:4:in `<top (required)>'
/usr/local/bundle/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `require'
/usr/local/bundle/gems/less-2.6.0/lib/less/java_script/v8_context.rb:2:in `<top (required)>'
/usr/local/bundle/gems/less-2.6.0/lib/less/java_script.rb:9:in `require'
/usr/local/bundle/gems/less-2.6.0/lib/less/java_script.rb:9:in `default_context_wrapper'
/usr/local/bundle/gems/less-2.6.0/lib/less/java_script.rb:17:in `context_wrapper'
/usr/local/bundle/gems/less-2.6.0/lib/less/loader.rb:13:in `initialize'
/usr/local/bundle/gems/less-2.6.0/lib/less.rb:14:in `new'
/usr/local/bundle/gems/less-2.6.0/lib/less.rb:14:in `<module:Less>'
/usr/local/bundle/gems/less-2.6.0/lib/less.rb:9:in `<top (required)>'
/usr/local/bundle/gems/less-rails-2.7.1/lib/less/rails.rb:6:in `require'
/usr/local/bundle/gems/less-rails-2.7.1/lib/less/rails.rb:6:in `<top (required)>'
/usr/local/bundle/gems/less-rails-2.7.1/lib/less-rails.rb:1:in `require'
/usr/local/bundle/gems/less-rails-2.7.1/lib/less-rails.rb:1:in `<top (required)>'
/app/config/application.rb:12:in `<top (required)>'
/app/Rakefile:4:in `require'
/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
The command '/bin/sh -c RAILS_ENV=production SECRET_KEY_BASE=secret bundle exec rake assets:precompile' returned a non-zero code: 1
```

**Comment by ignisf** [comment]
Please provide more information about the platform you're running this on. Also, there has been a new release of libv8 that should resolve many install issues.

**Comment by ignisf** [comment]
Closing for now, please reopen if you're still experiencing the issue
