### ISSUE TITLE
Unable to install on FreeBSD 10.1 with ruby 2.0.0

### ISSUE THREAD

**Issue by etolstoy** [cowboyd/therubyracer#407]
I'm trying to install `therubyracer` on FreeBSD:

```bash
gem install therubyracer
```

and get the following error:

```
ibv8-3.16.14.13/vendor/v8/Makefile" line 283: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 284: Need an operator
make: Fatal errors encountered -- cannot continue/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `each'
	from /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `verify_installation!'
	from /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'

make: stopped in /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8 Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
	ERROR: Failed to build gem native extension.

        /usr/local/bin/ruby20 extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.8
Using compiler: /usr/bin/c++ (clang version 3.4.1)
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 43: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 45: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 46: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 48: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 50: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 52: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 54: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 56: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 58: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 60: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 62: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 64: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 66: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 68: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 70: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 72: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 74: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 76: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 78: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 79: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 81: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 83: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 85: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 87: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 89: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 91: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 93: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 95: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 97: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 99: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 101: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 103: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 105: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 107: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 109: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 111: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 113: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 115: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 117: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 119: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 121: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 123: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 125: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 127: Missing dependency operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 129: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 280: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 281: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 283: Need an operator
make: "/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/Makefile" line 284: Need an operator
make: Fatal errors encountered -- cannot continue/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `each'
	from /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:35:in `verify_installation!'
	from /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'

make: stopped in /usr/local/lib/ruby/gems/2.0/gems/libv8-3.16.14.13/vendor/v8
```

FreeBSD version 10.1-STABLE-r273058
ruby version 2.0.0p576

**Comment by ignisf** [comment]
Hey, try to install GNU Make and try again

**Comment by ignisf** [comment]
Closing for now, feel free to reopen this issue if installing gmake does not solve it
