### ISSUE TITLE
Can't compile ruby on OS X 10.11.4

### ISSUE THREAD

**Issue by crtlabs** [cowboyd/therubyracer#408]
I've tried to install ruby not from binaries, as I was getting some cert errors.

This what happend

```
rvm reinstall 2.2.4 --disable-binary --with-gcc=/Applications/Xcode.app/Contents/Developer/usr/bin/gcc
ruby-2.2.4 - #removing src/ruby-2.2.4..
ruby-2.2.4 - #removing rubies/ruby-2.2.4..
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Warning: found user selected compiler '/Applications/Xcode.app/Contents/Developer/usr/bin/gcc', this will suppress RVM auto detection mechanisms.
Installing Ruby from source to: /Users/robertlabus/.rvm/rubies/ruby-2.2.4, this may take a while depending on your cpu(s)...
ruby-2.2.4 - #downloading ruby-2.2.4, this may take a while depending on your connection...
ruby-2.2.4 - #extracting ruby-2.2.4 to /Users/robertlabus/.rvm/src/ruby-2.2.4....
ruby-2.2.4 - #applying patch /Users/robertlabus/.rvm/patches/ruby/2.2.4/fix_installing_bundled_gems.patch.
ruby-2.2.4 - #configuring..........................................................
ruby-2.2.4 - #post-configuration.
ruby-2.2.4 - #compiling.............................................................
ruby-2.2.4 - #installing.............
Error running '__rvm_make install',
showing last 15 lines of /Users/robertlabus/.rvm/log/1461138944_ruby-2.2.4/install.log
	from /Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems/spec_fetcher.rb:42:in `fetcher'
	from /Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems/resolver/installer_set.rb:37:in `initialize'
	from /Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems/dependency_installer.rb:430:in `new'
	from /Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems/dependency_installer.rb:430:in `resolve_dependencies'
	from /Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems/dependency_installer.rb:373:in `install'
	from /Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems.rb:558:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-nodoc] Error 1
++ return 2
```

Note: skipping ---with-gcc also ends up the same.

**Comment by crtlabs** [comment]
Just to add more, log states:

```
installing bundle gems:       /Users/robertlabus/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
/Users/robertlabus/.rvm/src/ruby-2.2.4/lib/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/Users/robertlabus/.rvm/src/ruby-2.2.4/lib/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/robertlabus/.rvm/src/ruby-2.2.4/.ext/x86_64-darwin15/psych.bundle, 9): Library not loaded: /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (LoadError)
  Referenced from: /Users/robertlabus/.rvm/src/ruby-2.2.4/.ext/x86_64-darwin15/psych.bundle
```

Although I've installed it a while ago with:
```
rvm pkg install libyaml
```

**Comment by ignisf** [comment]
I don't see how this is related to therubyracer. Feel free to reopen this in case you find more info.
