### ISSUE TITLE
ERROR:  Error installing therubyracer

### ISSUE THREAD

**Issue by raky291** [cowboyd/therubyracer#424]
ERROR:  Error installing therubyracer

OS: Windows 7

```
C:\>gem install therubyracer
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
        ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby2.2.0/bin/ruby.exe -r ./siteconf20161213-6032-1j7hqmr.rb extconf.rb
creating Makefile
'patch' is not recognized as an internal or external command,
operable program or batch file.
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/patcher.rb:15:in `block (2 levels) in patch!': failed to apply patch C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/patches/disable-building-tests.patch (RuntimeError)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/patcher.rb:12:in `each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/patcher.rb:12:in `block in patch!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/patcher.rb:8:in `open'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/patcher.rb:8:in `patch!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/builder.rb:57:in `block in build_libv8!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/builder.rb:54:in `chdir'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/builder.rb:54:in `build_libv8!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/ext/libv8/location.rb:24:in `install!'
        from extconf.rb:7:in `<main>'
Applying C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17/patches/disable-building-tests.patch

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libv8-3.16.14.17 for inspection.
Results logged to C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/libv8-3.16.14.17/gem_make.out

```

**Comment by ignisf** [comment]
Hello, at this point `therubyracer` has no Windows support due to the `libv8` gem lacking such. Please take a look at https://github.com/cowboyd/libv8/issues/203 for more information.
