### ISSUE TITLE
TypeError when require'ing on Ruby 2.4

### ISSUE THREAD

**Issue by ddfreyne** [cowboyd/therubyracer#427]
On Ruby 2.4, `therubyracer` cannot be `require`d:

```
require 'therubyracer'
```

```
TypeError: wrong argument type Class (expected Module)
	from /usr/local/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include'
	from /usr/local/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
	from /usr/local/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
…
```

**Comment by ddfreyne** [comment]
This is already fixed in f2ccbad7e9e3899e8743624d9b1436500100420a!

**Comment by spickermann** [comment]
Great that this is already fixed. Thanks a lot.

What are your plans about releasing a new version via rubygems.org?

**Comment by ignisf** [comment]
I've pinged @cowboyd. Hopefully soon.

**Comment by ignisf** [comment]
https://github.com/cowboyd/therubyracer/issues/430 created for tracking the release
